### ISSUE TITLE
hmatrix indexed at 0

### ISSUE THREAD

**Issue by GregorySchwartz** [bgamari/hmatrix-svdlibc#3]
I'm getting incorrect results with the `sparseSvd` command which may be due to the fact that `hmatrix` now seems to use 0 indexing rather than 1 indexing, and the `shiftCSR` subtracts 1. More specifically, the SVD of
```
[ 1 1
  0 0
  0 0
  1 1 ]
```
does not match `hmatrix`'s svd.

I noticed that the CSR still uses the 1 index, so there may be a different cause for the issue.

**Comment by GregorySchwartz** [comment]
svdlibc reports the same result, so it's svdlibc's issue, probably a limitation in some way.

**Comment by bgamari** [comment]
Gregory Schwartz <notifications@github.com> writes:

> Closed #3.
>
Perhaps you would like to add a note to the documentation mentioning
this infelicity?

**Comment by GregorySchwartz** [comment]
I think it would be best to explicitly state the accuracy bounds of sparse SVD using their method, but unfortunately I'm not too familiar with the differences.
