### ISSUE TITLE
Outputs svd.in.m

### ISSUE THREAD

**Issue by GregorySchwartz** [bgamari/hmatrix-svdlibc#8]
Seems like a leftover from debugging, but should be removed (or optional, with the default not outputting it): `hmatrix-svdlibc-0.5.0/svdlibc/las2.c:  svdWriteSparseMatrix(A, "svd.in.m", SVD_F_DT);`. I don't see it on github, but it's on the version uploaded to hackage.

**Comment by GregorySchwartz** [comment]
Is there any way I can help with this issue? It just might need to be reuploaded with the version on github.

**Comment by bgamari** [comment]
Whoops. Thanks for pointing this out. Indeed it looks like my tree was dirty when I cut the release.

**Comment by bgamari** [comment]
Fixed in 0.5.0.1.
